#!/bin/python
# used google AI develop base clang logic to generate ext.h
# extended to generate ext.c 

import clang.cindex
import sys
import os

# --- (Optional) Manual configuration if libclang is not found automatically ---
# clang.cindex.Config.set_library_file('/usr/lib/llvm-14/lib/libclang.so') 

def get_function_prototype_ifunc(tu, cursor):
    """Extracts the full function prototype string for a declaration."""
    # Only process declarations in the specific input file
    print(cursor.kind, cursor.linkage, cursor.spelling);
    range_start = cursor.extent.start
    range_end = cursor.extent.end
    rettype_tokens   = []
    parms_tokens     = []
    signature_tokens = []
    count = 0
    name = -1
    for token in tu.get_tokens(extent=cursor.extent):
        signature_tokens.append(token.spelling)
        if token.spelling == cursor.spelling:
            name = count
            print(signature_tokens[name])
        elif name == -1:
            rettype_tokens.append(token.spelling)
        else:
            parms_tokens.append(token.spelling)
            count=count + 1
    if count != -1:  
        # Join the tokens to reconstruct the signature string
        # We remove the last token, the '{', to get just the declaration part
        rettype = " ".join(rettype_tokens).strip() if rettype_tokens else 'void'
        parms   = " ".join(parms_tokens).strip() if parms_tokens else 'void'
        parms   = parms[2:-2]
        parms   = parms.replace(' ,', ',')
        func    = cursor.spelling
        print("rettype:", rettype)
        print("name:", func)
        print("parms:", parms)
        return f"extern {rettype} {func}{parms};", f"DECLARE_IFUNC({func}, {rettype}, ({parms}))"
    else:
        return None,None
    
def get_global_variable_declaration(cursor):
    """Extracts the declaration string for a global variable."""
    var_name = cursor.spelling
    var_type = cursor.type.spelling
    return f"extern {var_type} {var_name};"

def process_files(source_filenames):
    """
    Processes multiple C files and aggregates declarations.
    """
    index = clang.cindex.Index.create()
    all_function_prototypes = set() # Use a set to avoid duplicate declarations
    all_ifuncs = set()
    all_global_variables = set()

    all_function_prototypes.add("extern void set_app_got(app_got_t* got);")  # Manually add set_app_got declaration

    for source_filename in source_filenames:
        print(f"Parsing {source_filename}...")
        # optionally add -nostdinc
        tu = index.parse(source_filename, args=['-nostdinc','-x', 'c', '-std=c99'],
                         options=clang.cindex.TranslationUnit.PARSE_INCOMPLETE)
        
        if not tu:
            print(f"Error: Unable to parse translation unit for {source_filename}. Skipping.")
            continue

        for cursor in tu.cursor.get_children():
            # Only consider declarations belonging to the current source file being parsed
            if cursor.location.file and os.path.abspath(cursor.location.file.name) != os.path.abspath(source_filename):
                continue

            if (cursor.kind == clang.cindex.CursorKind.FUNCTION_DECL and
                cursor.linkage == clang.cindex.LinkageKind.EXTERNAL and
                not cursor.is_definition()):
                prototype,ifunc = get_function_prototype_ifunc(tu, cursor)
                print("proto: ", prototype);
                if prototype:
                    all_function_prototypes.add(prototype)
                if ifunc:
                    all_ifuncs.add(ifunc)
                    
            elif cursor.kind == clang.cindex.CursorKind.VAR_DECL:
                # Filter out static variables and local variables
                #if cursor.linkage == clang.cindex.Linkage.EXTERNAL and cursor.is_definition():
                declaration = get_global_variable_declaration(cursor)
                if declaration:
                    all_global_variables.add(declaration)
                        
    return sorted(list(all_global_variables)), sorted(list(all_function_prototypes)), sorted(list(all_ifuncs))

def write_files(c_filename, includes, global_vars, func_protos, ifuncs):
    """Writes the ifuncs to a single source file."""
    c_content = []
    for inc in includes:
        c_content.append(f"#include \"{inc}\"")
  
    c_content.extend([
        "",
        "extern void *dpld_resolver(char * symbol_name);",
        "",
        "// macro to define a function as an ifunc and to define a simple",
        "// resolver that calls the base_resolver",
        "#define DECLARE_IFUNC(name, rettype, args) \\",
        "   rettype name args __attribute__((ifunc(#name \"_resolver\"))); \\",
        "   static rettype (*name##_resolver(void)) args { \\",
        "      return (rettype (*) args) dpld_resolver(#name); \\",
        "   } ",
        ""
    ])
    
    if ifuncs:
        c_content.append("// generate ifunc for ext function found");
        c_content.extend(ifuncs)
        c_content.append("");
        
    with open(c_filename, 'w') as f:
        f.write('\n'.join(c_content))
        
    print(f"\nSuccessfully generated: {c_filename}")

def write_app_files(header_filename, func_protos, got_declarations, function_definitions, func_names):
    """Writes the app file with function prototypes and GOT declarations."""
    include_guard = os.path.basename(header_filename).replace('.', '_').upper() + "_"
    header_content = [
        f"#ifndef {include_guard}",
        f"#define {include_guard}",
        "",
        "#ifdef __cplusplus",
        "extern \"C\" {",
        "#endif",
        "",
        "#define SET_APP_GOT_FUNC(func_name) \\",
        "    app_got->func_name = (void *)&func_name;",
        "",
        "#ifdef __KERNEL__",
        "#define DEFINE_GOT_FUNC(func_name, rettype, args) \\",
        "static inline rettype func_name args { \\",
        "asm volatile ( \\",
        "   \"jmp *%0\" \\",
        "   : \\",
        "   : \"r\"(app_got->func_name) \\",
        "   ); \\",
        "   unreachable(); \\",
        "}",
        "",
        "#endif"
    ]

    if not got_declarations:
        got_declarations.append("void* dummy; // No GOT entries found, dummy entry to avoid empty struct")
        header_content.append("#define NO_APP_GOT_ENTRIES")

    if got_declarations:
        header_content.append("typedef struct {")
        header_content.append("// GOT Declarations")
        header_content.extend(got_declarations)
        header_content.append("} app_got_t;")
        header_content.append("")

        
    header_content.append("#ifdef __KERNEL__")
    header_content.append("extern app_got_t* app_got;")
    header_content.append("#endif")

    if function_definitions:
        header_content.append("")
        header_content.append("#ifdef __KERNEL__")
        header_content.append("// Function Definitions")
        header_content.extend(function_definitions)
        header_content.append("#endif")

    if func_protos:
        header_content.append("")
        header_content.append("#ifdef DECLARE_ALL_FUNCS")
        header_content.append("// Function Prototypes")
        header_content.extend(func_protos)

        header_content.append("")
        header_content.append("//Set GOT logic")
        header_content.append("#define SET_ALL_GOT_ENTRIES() \\")

        for func_name in func_names:
            header_content.append(f"SET_APP_GOT_FUNC({func_name}); \\")
        
        header_content.append("")
        header_content.append("#endif")
        header_content.append("")
    
    else:
        # noop macro
        header_content.append("#define SET_ALL_GOT_ENTRIES() // No functions found, no GOT entries to set")

    header_content.extend([
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        f"#endif // {include_guard}"
    ])

    with open(header_filename, 'w') as f:
        f.write('\n'.join(header_content))

        
    print(f"\nSuccessfully generated: {header_filename}")



if __name__ == "__main__":
    # sys.argv[0] is the script name, sys.argv[1:] is the list of source files

    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output.c> <file1.h> [file2.h ...]")
        sys.exit(1)
    
    output_c_name = sys.argv[1]
    source_files = sys.argv[2:]

    # Filter to ensure only .kh files are processed (optional safety check)
    kh_files = [f for f in source_files if f.endswith('.kh')]
    if not kh_files:
        print("Error: No valid .kh files provided for processing.")
        sys.exit(1)
            
    globals_list, functions_list, ifunc_list = process_files(kh_files)
    write_files(output_c_name, kh_files, globals_list, functions_list, ifunc_list)
