#!/bin/bash
pushd valkey

if [ ! -f "libkallsyms.so" ]; then
    sudo cp /proc/libkallsyms.so .
fi

CONFIG_FILE="valkey.conf"

#check -g flag to this script
if [[ "$@" != *"-g"* ]]; then
    COMMAND="sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. $1 $CONFIG_FILE"    
else
    COMMAND="sudo env -i LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. gdb $2 $CONFIG_FILE"
fi



echo $COMMAND
$COMMAND

popd


# set environment LD_LIBRARY_PATH=/home/user/Symbi-OS/Symlib/dynam_build:/home/user/Symbi-OS/Symlib/dynam_build:/home/user/Symbi-OS/Symlib/dynam_build:/home/user/Symbi-OS/examples/valkey/valkey
# set environment LD_BIND_NOW=1